version: '3'
services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    networks:
      - invidious
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_PASSWORD: kemal
      POSTGRES_USER: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
  invidious:
    build:
      context: .
      dockerfile: docker/Dockerfile.arm64
    restart: unless-stopped
    mem_limit: 1024M
    networks:
      - invidious
    volumes:
      - /var/run/invidious-docker/:/var/run/invidious/:rw
    environment:
      # Adapted from ./config/config.yml
      INVIDIOUS_CONFIG: |
        channel_threads: 1
        check_tables: true
        feed_threads: 1
        db:
          user: kemal
          password: kemal
          host: postgres
          port: 5432
          dbname: invidious
        use_quic: true
        decrypt_polling: false
        full_refresh: false
        https_only: false
        registration_enabled: false
        domain:
        force_resolve: ipv4
        bind_unix: /var/run/invidious/invidious.sock
        popular_enabled: false
        statistics_enabled: true
        default_user_preferences:
          comments:
          - youtube
          - ""
          feed_menu:
          - Subscriptions
          - Playlists
          default_home: none
    depends_on:
      - postgres

volumes:
  postgresdata:

networks:
  invidious:
